In [1]:
import numpy as np


In [3]:
arry = [1,2,3,4,5]
arry2 = arry[::-1]
arry2

[5, 4, 3, 2, 1]

In [5]:
# 15 - Create a 2d array with 1 on the border and 0 inside (创建2维数组，边界处元素值为1而内部元素值为0)
z = np.ones((4,4))
z

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [6]:
z[1:-1, 1:-1] = 0
z

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [12]:
# 19 - Create a 8x8 matrix and fill it with a checkerboard pattern (创建8x8的2维数组，按照棋盘的黑白相间的格式以1和0交替填充该数组)
z = np.ones((8,8))
z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [13]:
z[::2, ::2] = 0
z[1::2, 1::2] = 0
z

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [14]:
# 70 - Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (现有数组[1，2，3，4，5]，如何构建新数组，在原数组的每两个数之间插入3个连续的0)
arr = np.array([1,2,3,4,5])
arr2 = np.zeros(len(arr) + (len(arr) - 1)*3)
arr2[::4] = arr
arr2

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
        0.,  0.,  0.,  5.])